name: Dispatch Preview

on:
    workflow_dispatch:
      inputs:
        runId:
          required: true
          description: 'ID of the action to pull artifacts from'
        build:
          required: true
          description: 'Build number for the release'
        version:
          required: true
          description: 'Version under which to upload to the Downloads API'

jobs:
  dispatch-preview:
    # Allow access to secrets if we are uploading a preview
    secrets: inherit
    uses: GeyserMC/actions/.github/workflows/upload-preview.yml@master
    with:
      build: ${{ inputs.build }}
      version: ${{ inputs.version }}
      files: |
        bungeecord:Geyser-BungeeCord.jar
        fabric:Geyser-Fabric.jar
        neoforge:Geyser-NeoForge.jar
        spigot:Geyser-Spigot.jar
        standalone:Geyser-Standalone.jar
        velocity:Geyser-Velocity.jar
        viaproxy:Geyser-ViaProxy.jar
      project: geyserpreview
      runId: ${{ inputs.runId }}